name: dotnet package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Install mono
        run: |
          sudo apt-get install gnupg ca-certificates
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
          echo "deb https://download.mono-project.com/repo/ubuntu stable-focal main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
          sudo apt-get update
          sudo apt-get install mono-devel
      - name: Build project
        run: |
          sudo mcs *.cs
          
